### ISSUE TITLE
Hmn

### ISSUE THREAD

**Issue by AndreTheGamer** [PocketPanel/PocketPanel#2]
Can i continue this? seems like a unique idea

**Comment by TheKillerTacos** [comment]
Im working on another and better panel, "PocketMine Advanced", will be writen on C#, by now on VB.net, since it will be for simple features, and if you can, you may go, ill just change few things

**Comment by AndreTheGamer** [comment]
I can't help with  "PocketMine Advanced" since i don't know C# . But again, i think we should continue working on this :)  

start with the basics, and improv!

**Comment by AndreTheGamer** [comment]
@TheKillerTacos  Eh, is it okay if i create a new organization for it? but the project will still be maintain by the "TKRT-Creations"     :)

**Comment by TheKillerTacos** [comment]
Named changed, CraftPanel Advance, an advanced panel to manage servers, like minimaps (may use Mineways code but is python, also is MCEDit, ill check it out later), kick ban players, Just like a panel with more features, and more accurate Stats than PocketStats, but im still working on features,

Yes you can, only License is Apache 2.0,

**Comment by AndreTheGamer** [comment]
@TheKillerTacos How about ujm

'PocketPanel" for the name :+1:

**Comment by TheKillerTacos** [comment]
ok
PocketPanel - The free edition, No MiniMap,
PocketPanel Advance - Premium edition - $5 Monthly, Live Minimap (if possible), Instant support, and other

**Comment by AndreTheGamer** [comment]
Ya, we can prob have plans? the basic - free edition and the advance paid one :)

**Comment by TheKillerTacos** [comment]
Yep

**Comment by AndreTheGamer** [comment]
@TheKillerTacos  I've just invited you it as "owner"!

**Comment by TheKillerTacos** [comment]
ok, let me transfer the Project,

**Comment by AndreTheGamer** [comment]
ok.

**Comment by TheKillerTacos** [comment]
and also, ill delete "TKRT-Creations", and just make the projects like, PocketSkyblock or like that, since TKRT Creations would be more on creations, not Open Source Projects, im also making a Simple, low poly style, racing game for android, and will release it with this name, so, yep

**Comment by AndreTheGamer** [comment]
ok :)

**Comment by TheKillerTacos** [comment]
Go to new issue, made Conversation.
